---
sidebar: sidebar 
permalink: alerts-start-setup.html 
keywords: bluexp, alerts, ontap, netapp 
summary: Per utilizzare gli avvisi BlueXP , eseguire alcuni passaggi per configurarli. 
---
= Impostare gli avvisi BlueXP 
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Per utilizzare gli avvisi BlueXP , eseguire alcuni passaggi per configurarli.

Prima di iniziare, verificare link:alerts-start-prerequisites.html["prerequisiti"]che l'ambiente sia pronto.

Revisione https://docs.netapp.com/us-en/cloud-manager-setup-admin/reference-checklist-cm.html["Requisiti standard di BlueXP"^].



== Accesso alle risorse del cluster

Per visualizzare gli avvisi, l'utente connesso deve far parte dell'organizzazione BlueXP  e disporre dell'accesso necessario alla risorsa cluster.



== Crea un connettore BlueXP

Contattare il rappresentante di vendita NetApp per provare o utilizzare questo servizio. Quindi, quando si utilizza il connettore BlueXP , verranno incluse le funzionalità appropriate per il servizio avvisi.

Per creare un connettore in BlueXP  prima di utilizzare il servizio, fare riferimento alla documentazione di BlueXP  che descrive https://docs.netapp.com/us-en/cloud-manager-setup-admin/concept-connectors.html["Come creare un connettore BlueXP"^].

Dopo aver configurato il connettore e aggiunto l'ambiente di lavoro, attendere circa 15 minuti per il rilevamento iniziale.
